version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-root}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  products-api:
    depends_on: 
      - postgres
    build:
      context: .
    container_name: products-api
    hostname: products-api
    ports:
      - 80:8080
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-root}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    command: --env-file $(pwd)/.env
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  db:
    driver: local