consumes:
    - application/json
definitions:
    product:
        type: object
        required:
            - code
            - price
        properties:
            code:
                type: string
                format: string
            price:
                type: integer
                format: uint
paths:
  /:
    get:
      tags:
        - products
      responses:
        200:
          description: list the products
          schema:
            type: array
            items:
              $ref: "#/definitions/product"

info:
    description: Products API
    title: Products API
    version: 1.0.0
paths: {}
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
